version: '3'

services:
  brh:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./json:/app/json
      - ./docs:/app/docs
      - ./run.sh:/app/run.sh
    environment:
      APP_NAME: ${APP_NAME:-app}
      PROJECT_NAME: ${PROJECT_NAME:-测试系统}

